"""empty message

Revision ID: 1154d772c336
Revises: d714f8f7d8ca
Create Date: 2022-10-30 01:25:38.279686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1154d772c336'
down_revision = 'd714f8f7d8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleado', sa.Column('telefono', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleado', 'telefono')
    # ### end Alembic commands ###
