"""empty message

Revision ID: 19c59437ced1
Revises: 1154d772c336
Create Date: 2022-10-30 01:43:48.518958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c59437ced1'
down_revision = '1154d772c336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleado', 'telefono')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleado', sa.Column('telefono', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
