"""empty message

Revision ID: 8c5778aa25cd
Revises: 19c59437ced1
Create Date: 2022-10-30 12:24:55.638389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5778aa25cd'
down_revision = '19c59437ced1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoologico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('cantidad_animales', sa.Integer(), nullable=True),
    sa.Column('cantidad_guias', sa.Integer(), nullable=True),
    sa.Column('cantidad_cuidadores', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoologico')
    # ### end Alembic commands ###
